<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <TargetFramework>net10.0-browser</TargetFramework>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <WasmExtraFilesToDeploy Include="wwwroot\**" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseAvaloniaFork)' == 'False'">
    <PackageReference Include="Avalonia.Browser" />
    <PackageReference Include="ReactiveUI" />
    <PackageReference Include="Avalonia.Browser" VersionOverride="$(AvaloniaSampleVersion)" />
  </ItemGroup>

  <!-- iPlus settings and overrides -->
  <Import Condition="'$(UseAvaloniaFork)' == 'True'" Project="../../../iPlus/build/AvaloniaInclude.props" />
  <Import Condition="'$(UseAvaloniaFork)' == 'True'" Project="../../../iPlus/build/AvaloniaBaseBrowserInclude.props" />
  <!-- End iPlus settings and overrides -->

  <ItemGroup>
    <ProjectReference Include="..\Avalonia.Labs.Catalog\Avalonia.Labs.Catalog.csproj" />
  </ItemGroup>
</Project>
